name: Deploy to Firebase Hosting on Push

on:
  push:
    branches:
      - master  # Change this to any branch you prefer, like '*' for all branches.

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: flutter pub get && flutter build web && flutter build ios && flutter build android
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_AI_BUSINESS_PLATFORM }}
          projectId: ai-business-platform
